<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Buysell</title>
</head>
<body>
<h1>Buysell</h1> <hr>
<h4>Подробная информация о товаре</h4>
<#list images as img>
    <img src="/images/${img.id}" height="60px"/><br><br>
</#list>

<b>Название товара:</b>${product.title}<br/>
<b>Описание товара:</b>${product.description}<br/>
<b>Цена:</b>${product.price}<br/>
<b>Город:</b>${product.city}<br/>
<b>Автор:</b>${product.author}<br/>
<hr>
<h3>Создать новый товар</h3>
<form action="/product/delete${product.id}" method="post">

    <input type="submit" value="Удалить товар"/>


</form>
</body>
</html>